### ISSUE TITLE
In-memory data loading 

### ISSUE THREAD

**Issue by bigdatabaracus** [NervanaSystems/aeon#45]
Hi, I'm trying to do inference with neon deepspeech for pcm audio data residing in-memory (audio transcription). The way I'm currently doing this is writing the data to disk, generating an on-the-fly manifest file and feeding that to the aeon data loader. This seems unnecessary cumbersome, however, to ensure that all the same transformations are applied to the audio data during inference as during training, I haven't figured out a better way. 

My question: is there a way to applying same the audio transcription transformations that aeon does during training for in-memory data without going via disk? 

More specifically, I'm using the default mfsc features of neon deep speech implementation. I'm guessing, based on a comment in aeon's source code that the transformations could be computed with the implemenation provided in https://github.com/jameslyons/python_speech_features though no mel-frequency spectral coefficients (MFSC) named transformation is mentioned in the project. Perhaps the filterbank features of python_speech_features are equivalent to mel-frequency spectral coefficients in aeon, however, i'm not sure if the defaults there are similar?

Thanks a lot.

**Comment by apark263** [comment]
yes, that certainly seems like a roundabout way to go.  we should really provide the pathways to compute the necessary extraction and transformations in memory, since the code is right there.

in particular, the extraction part: 
https://github.com/NervanaSystems/aeon/blob/master/loader/src/etl_audio.cpp#L35

and the conversion to features part:
https://github.com/NervanaSystems/aeon/blob/master/loader/src/etl_audio.cpp#L65

Unfortunately we haven't made any library functions to expose these to the python interface just yet.

I think jameslyons' library would work just fine as long as you match the parameters used to compute the FFT, and the parameters used to create the filterbanks (this is the mel scale).  Then you want to use the `logfbank` function and make sure that the dynamic range of the values are scaled appropriately.

you can see our defaults listed in:
https://github.com/NervanaSystems/aeon/blob/master/loader/src/etl_audio.hpp

Combine as needed with the configurations provided by the deepspeech implementation

**Comment by bigdatabaracus** [comment]
Thank you @apark263 for your answer earlier. Getting back working on this I was able to reproduced the required audio preprocessing with jameslyons' library. For anybody interested, here’s how I did it. 

```
from python_speech_features import fbank
from scipy.signal.windows import hann
import numpy as np
import cv2 as cv

sig = …

feat,energy = fbank(sig,16000,nfilt=13,preemph=0,winfunc=hann,nfft=400)
log_fbank = np.log(feat[:-1,:])
cv.normalize(log_fbank, log_fbank, 0, 255, cv.NORM_MINMAX)
log_fbank = np.round(log_fbank)

```
After this you will need to of course apply padding and transpose the features to the correct shape for feeding them to the model.

Thanks again!
