### ISSUE TITLE
Installing Aeon on CentOS 7 without root access

### ISSUE THREAD

**Issue by felipheggaliza** [NervanaSystems/aeon#57]
Hi, 

I am trying to install Aeon using the commands:

`git clone https://github.com/NervanaSystems/aeon.git`

`mkdir -p aeon/build && cd $_ && cmake .. && pip install .`

But I got this error:

CMake Error: your CXX compiler: "clang++" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
-- Configuring incomplete, errors occurred!
See also "/home/feliphegaliza/aeon/build/CMakeFiles/CMakeOutput.log".
See also "/home/feliphegaliza/aeon/build/CMakeFiles/CMakeError.log".

How can I solve this dependency on CentOS 7 without root access?

**Comment by mrysztow** [comment]
This is not specific for Aeon, but general, how to install packages in the system without root access.

I can think about two possible solutions, but without guarantee that it will work for you, so you risk it on your own (no support from our side):
-run docker container with all required prerequisites installed (but your root must permit you usage of docker containers)
-download manually all required prerequisites (and their dependencies) as rpms and decode them in your ~ instead of installing them into /. With proper set paths (so ~/bin ~/lib  etc. are visible) you may be lucky to run a compilation process.

**Comment by pzelazko-intel** [comment]
closing it as there is no response
